# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Development Containers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
          - "httpx*"
      development-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "*test*"

  # Node.js dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: "tuesday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        patterns:
          - "*"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 5

  # Terraform Bootstrap
  - package-ecosystem: "terraform"
    directory: "/terraform/bootstrap"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "09:30"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 3

  # Docker (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: "thursday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "Bornegrim"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
